version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
        - name: product
          identifier: raw_gz_product
          description: products of Greenweez / On row per product-id and purchase_price
          columns:
            - name: products_id
              description: Unique products_id
              tests:
                - unique
                - not_null
            - name: purchase_price
              description: Purchase price of the products
        - name: sales
          identifier: raw_gz_sales
          description: sales of Greenweez / we have on row per product_id found in each orders_id
          # Freshness testing
          loaded_at_field: "CAST(date_date AS TIMESTAMP)"
          freshness:
            warn_after: {count: 90, period: day}
          columns:
            - name: date_date
              description: date of purchase
            - name: orders_id
              description: orders_id for each product_id
            - name: products_id
              description: product_id for each product in each order
            - name: revenue
              description: revenue generated by product in each order
            - name: quantity
              description: quantity of product_id in each order
          tests:
            - unique:
                column_name: "(orders_id || '_' || pdt_id)"
        - name: ship
          identifier: raw_gz_ship
          description: shipping_fee, log_cost and ship_cost per orders_id
          columns:
            - name: orders_id
              description: unique orders_id
              tests:
                - unique
                - not_null
            - name: shipping_fee
              description: shipping fees paid by the customer for each order
            - name: logcost
              description: logistics costs per order
            - name: ship_cost
              description: shipping cost for each order